from typing import Any, Dict
from fastapi import APIRouter
from app.schemas.analytics import (
    AIClassifyRequest,
    AIClassifyResponse,
    AIPriorityRequest,
    AIPriorityResponse
)

router = APIRouter()

CIVIC_CATEGORIES = {
    "Roads & Infrastructure": ["road", "pothole", "asphalt", "divider", "footpath", "sidewalk", "speed breaker", "cracked", "pavement"],
    "Sanitation & Waste Management": ["garbage", "trash", "waste", "dump", "stench", "litter", "debris", "compost", "uncollected"],
    "Electrical & Streetlighting": ["street light", "streetlight", "pole", "wire", "sparking", "transformer", "dark", "lamp", "blackout", "electricity"],
    "Water Supply & Drainage": ["water", "pipeline", "leak", "pipe", "drainage", "sewage", "overflow", "manhole", "tap", "drinking water", "flooding"],
    "Public Health & Safety": ["stray", "dog", "mosquito", "hazard", "fire", "smoke", "unsafe", "open wire", "accident"]
}

EMERGENCY_TRIGGERS = [
    "sparking", "live wire", "open manhole", "explosion", "fire", "cave in", "burst pipe",
    "electric shock", "major accident", "submerged", "gas leak", "structural collapse"
]

@router.post("/classify-complaint", response_model=AIClassifyResponse)
def classify_complaint(req: AIClassifyRequest) -> Any:
    """
    Proposed AI Service Endpoint:
    Simulates NLP-based complaint categorization (planned using fine-tuned BERT/DistilBERT).
    Provides clear transparency and academic demonstration.
    """
    text = f"{req.title} {req.description}".lower()

    scores = {}
    matched_words = []
    for cat, keywords in CIVIC_CATEGORIES.items():
        count = 0
        for kw in keywords:
            if kw in text:
                count += 1
                matched_words.append(kw)
        scores[cat] = count

    best_cat = max(scores, key=scores.get) if any(scores.values()) else "Roads & Infrastructure"
    score_val = scores.get(best_cat, 0)
    confidence = min(0.96, 0.72 + (score_val * 0.08)) if score_val > 0 else 0.65

    return AIClassifyResponse(
        predicted_category=best_cat,
        confidence_score=round(confidence, 2),
        is_simulated=True,
        proposed_model="Fine-tuned DistilBERT / BERT for Multi-Class Civic NLP",
        suggested_departments=[best_cat],
        detected_keywords=list(set(matched_words)),
        disclaimer="[CSP First Review Phase]: This prediction is generated by the AI architecture demo engine. The production pipeline is planned for implementation in Phase 2 as detailed in Slide 12 of the project review."
    )

@router.post("/detect-priority", response_model=AIPriorityResponse)
def detect_priority(req: AIPriorityRequest) -> Any:
    """
    Proposed AI Service Endpoint:
    Estimates civic issue priority and risk factor urgency.
    """
    text = f"{req.title} {req.description}".lower()

    detected_risks = [trigger for trigger in EMERGENCY_TRIGGERS if trigger in text]

    if req.is_emergency_flagged or len(detected_risks) >= 2:
        priority = "Emergency"
        urgency = 0.95
    elif len(detected_risks) == 1 or any(k in text for k in ["urgent", "severe", "huge", "dangerous", "broken"]):
        priority = "High"
        urgency = 0.82
    elif any(k in text for k in ["slow", "minor", "small", "paint"]):
        priority = "Low"
        urgency = 0.35
    else:
        priority = "Medium"
        urgency = 0.58

    return AIPriorityResponse(
        estimated_priority=priority,
        urgency_score=round(urgency, 2),
        is_simulated=True,
        proposed_model="MobileBERT + Civic Heuristic Risk Profiler",
        risk_factors=detected_risks,
        disclaimer="[CSP First Review Phase]: Priority detection is demonstrated as part of the proposed AI pipeline. Official emergency situations must be reported directly to municipal emergency dispatch."
    )

@router.get("/architecture-info")
def get_architecture_info() -> Dict[str, Any]:
    return {
        "status": "Proposed Architecture (Slide 12 - Layer 6)",
        "project_stage": "CSP First Review 2025-2026",
        "team": "M. Mahitha, C. Sindhu, B. Vijayasankar, D. Rajesh",
        "guide": "Dr M. Vijay",
        "institution": "Kalasalingam Academy of Research and Education",
        "proposed_components": [
            {
                "module": "Text NLP Classification",
                "target_model": "Fine-tuned DistilBERT / BERT",
                "purpose": "Automatic categorization of complaints into Roads, Sanitation, Electrical, Water, Health",
                "reference": "Caldeira et al. (2022) / Joshi et al. (2025 Cityzen)"
            },
            {
                "module": "Priority Detection",
                "target_model": "MobileBERT with Urgency Heuristics",
                "purpose": "Risk assessment and automated escalation of critical civic hazards",
                "reference": "Slide 4 (Objective 8) & Slide 17"
            },
            {
                "module": "Visual Road & Damage Inspection",
                "target_model": "MobileNetV2 / ResNet-50 / YOLOv8",
                "purpose": "Pothole, debris, and structural damage detection from citizen evidence photos",
                "reference": "Madan et al. (2026) / Cao et al. (2020 RDD)"
            },
            {
                "module": "Duplicate Complaint Clustering",
                "target_model": "Sentence Transformers + Geospatial Radius Matching",
                "purpose": "Cluster complaints reported by multiple citizens in the same geographic radius",
                "reference": "Slide 17 (Future Enhancement #4)"
            }
        ]
    }
